---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: file-repository
  name: file-repository
spec:
  ports:
    - name: "9594"
      port: 9594
      targetPort: 9594
  selector:
    io.kompose.service: file-repository
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: file-repository
  name: file-repository
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: file-repository
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: file-repository
    spec:
      containers:
        - image: dronahq/dronahq-self-hosted-file-repository
          name: dronahq-self-hosted-file-repository
          ports:
            - containerPort: 9594
          resources: {}
          volumeMounts:
            - mountPath: /app/.env
              name: file-repository-claim0
              readOnly: true
            - mountPath: /app/files
              name: file-repository-claim1
            - mountPath: /app/private
              name: file-repository-claim2
      restartPolicy: Always
      volumes:
        - name: file-repository-claim0
          persistentVolumeClaim:
            claimName: file-repository-claim0
            readOnly: true
        - name: file-repository-claim1
          persistentVolumeClaim:
            claimName: file-repository-claim1
        - name: file-repository-claim2
          persistentVolumeClaim:
            claimName: file-repository-claim2
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: file-repository-claim2
  name: file-repository-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: file-repository-claim1
  name: file-repository-claim1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: file-repository-claim0
  name: file-repository-claim0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
