---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "8080"
      port: 8080
      targetPort: 80
  selector:
    io.kompose.service: webserver
status:
  loadBalancer: {}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
    spec:
      containers:
        - env:
            - name: AUDITLOG_URL
              valueFrom:
                configMapKeyRef:
                  key: AUDITLOG_URL
                  name: dronahq-env
            - name: BUILDER_URL
              valueFrom:
                configMapKeyRef:
                  key: BUILDER_URL
                  name: dronahq-env
            - name: DEVICEAPI_URL
              valueFrom:
                configMapKeyRef:
                  key: DEVICEAPI_URL
                  name: dronahq-env
            - name: DHQ_AUDIT_LOG_MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DHQ_AUDIT_LOG_MYSQL_DATABASE
                  name: dronahq-env
            - name: DHQ_AUDIT_LOG_MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: DHQ_AUDIT_LOG_MYSQL_HOST
                  name: dronahq-env
            - name: DHQ_AUDIT_LOG_MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DHQ_AUDIT_LOG_MYSQL_PASSWORD
                  name: dronahq-env
            - name: DHQ_AUDIT_LOG_MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: DHQ_AUDIT_LOG_MYSQL_PORT
                  name: dronahq-env
            - name: DHQ_AUDIT_LOG_MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: DHQ_AUDIT_LOG_MYSQL_USER
                  name: dronahq-env
            - name: DHQ_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_DATABASE
                  name: dronahq-env
            - name: DHQ_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_HOST
                  name: dronahq-env
            - name: DHQ_MONGODB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_PASSWORD
                  name: dronahq-env
            - name: DHQ_MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_PORT
                  name: dronahq-env
            - name: DHQ_MONGODB_USER
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_USER
                  name: dronahq-env
            - name: DHQ_MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_DATABASE
                  name: dronahq-env
            - name: DHQ_MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_HOST
                  name: dronahq-env
            - name: DHQ_MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_PASSWORD
                  name: dronahq-env
            - name: DHQ_MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_PORT
                  name: dronahq-env
            - name: DHQ_MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_USER
                  name: dronahq-env
            - name: FILEREPOSITORY_URL
              valueFrom:
                configMapKeyRef:
                  key: FILEREPOSITORY_URL
                  name: dronahq-env
            - name: LICENSE_KEY
              valueFrom:
                configMapKeyRef:
                  key: LICENSE_KEY
                  name: dronahq-env
            - name: MONGO_INITDB_PWD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_PWD
                  name: dronahq-env
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: dronahq-env
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: dronahq-env
            - name: MONGO_INITDB_USER
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_USER
                  name: dronahq-env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: dronahq-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: dronahq-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: dronahq-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: dronahq-env
            - name: RUNAPI_URL
              valueFrom:
                configMapKeyRef:
                  key: RUNAPI_URL
                  name: dronahq-env
            - name: SSL_DOMAIN
              valueFrom:
                configMapKeyRef:
                  key: SSL_DOMAIN
                  name: dronahq-env
            - name: WEBAPP_URL
              valueFrom:
                configMapKeyRef:
                  key: WEBAPP_URL
                  name: dronahq-env
          image: nginx
          name: dronahq-self-hosted-webserver
          ports:
            - containerPort: 80
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/templates/default.conf.template
              name: webserver-claim0
              readOnly: true
            - mountPath: /var/www/certbot/
              name: webserver-claim1
              readOnly: true
            - mountPath: /etc/nginx/ssl/
              name: webserver-claim2
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: webserver-claim0
          persistentVolumeClaim:
            claimName: webserver-claim0
            readOnly: true
        - name: webserver-claim1
          persistentVolumeClaim:
            claimName: webserver-claim1
            readOnly: true
        - name: webserver-claim2
          persistentVolumeClaim:
            claimName: webserver-claim2
            readOnly: true
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webserver-claim2
  name: webserver-claim2
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webserver-claim1
  name: webserver-claim1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webserver-claim0
  name: webserver-claim0
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
status: {}
