services:

  mysqldb:
    image: mysql:oracle
    container_name: dronahq-module-mysqldb
    platform: linux
    restart: always
    env_file: app.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./init/mysql-init.sql:/docker-entrypoint-initdb.d/schema.sql:ro
      - ./storage/mysql:/var/lib/mysql
      - ./init/my.cnf:/etc/mysql/conf.d/my.cnf:ro
    ports:
      - 3306:3306

  mongodb:
    image: mongo:5.0.11
    container_name: dronahq-module-mongodb
    platform: linux
    restart: always
    env_file: app.env
    volumes:
      - ./init/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - ./init/mongodump:/mongodump
      - ./storage/mongodb:/data/db
    ports:
      - 27017:27017

  webserver:
    image: nginx
    container_name: dronahq-module-webserver
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
      - 443:443

  module1:
    image: module1
    container_name: dronahq-module1
    restart: always
    volumes:
      - ./app.env:/app/.env:ro
    ports:
      - 8091:8090

  module2:
    image: module2
    container_name: dronahq-module2
    restart: always
    volumes:
      - ./app.env:/app/.env:ro
    ports:
      - 8092:8090
