apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.27.0 (b0ed6a2c9)
  creationTimestamp: null
  labels:
    io.kompose.service: mysqldb
  name: mysqldb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysqldb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.27.0 (b0ed6a2c9)
      creationTimestamp: null
      labels:
        io.kompose.service: mysqldb
    spec:
      containers:
        - args:
            - --default-authentication-plugin=mysql_native_password
          env:
            - name: DHQ_MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_DATABASE
                  name: app-env
            - name: DHQ_MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_HOST
                  name: app-env
            - name: DHQ_MONGODB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_PASSWORD
                  name: app-env
            - name: DHQ_MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_PORT
                  name: app-env
            - name: DHQ_MONGODB_USER
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MONGODB_USER
                  name: app-env
            - name: DHQ_MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_DATABASE
                  name: app-env
            - name: DHQ_MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_HOST
                  name: app-env
            - name: DHQ_MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_PASSWORD
                  name: app-env
            - name: DHQ_MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_PORT
                  name: app-env
            - name: DHQ_MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: DHQ_MYSQL_USER
                  name: app-env
            - name: MONGO_INITDB_PWD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_PWD
                  name: app-env
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: app-env
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: app-env
            - name: MONGO_INITDB_USER
              valueFrom:
                configMapKeyRef:
                  key: MONGO_INITDB_USER
                  name: app-env
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_DATABASE
                  name: app-env
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_PASSWORD
                  name: app-env
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_ROOT_PASSWORD
                  name: app-env
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  key: MYSQL_USER
                  name: app-env
          image: mysql:oracle
          name: dronahq-module-mysqldb
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d/schema.sql
              name: mysqldb-claim0
              readOnly: true
            - mountPath: /var/lib/mysql
              name: mysqldb-claim1
            - mountPath: /etc/mysql/conf.d/my.cnf
              name: mysqldb-claim2
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mysqldb-claim0
          persistentVolumeClaim:
            claimName: mysqldb-claim0
            readOnly: true
        - name: mysqldb-claim1
          persistentVolumeClaim:
            claimName: mysqldb-claim1
        - name: mysqldb-claim2
          persistentVolumeClaim:
            claimName: mysqldb-claim2
            readOnly: true
status: {}
